#!/usr/bin/env python

from six.moves import input
from Board import Board

def alternate_player(current_player):
    if current_player == board.BLACK:
        return board.WHITE
    return board.BLACK

def render(board_matrix):
    board_rep = ''
    pos_hdr = ' '
    for pos in range(len(board_matrix)):
        pos_hdr += '| {}'.format(pos)
        
    hr = '--------------------------\n'

    board_rep += pos_hdr + '|\n' + hr
    for pos, row in enumerate(board_matrix):
        board_rep += '{}|'.format(pos) + '|'.join(row) + '|\n'
        board_rep += hr

    print(board_rep)

def validate_proposed_move(proposed_move):
    try:
        return (int(proposed_move[0]), int(proposed_move[2]))
    except:
        print("Move must be in row,col format. Ex: 5,4") 

board = Board()

current_player = board.BLACK # Black moves first
legal_moves = board.find_legal_moves(current_player)

proposed_move = False

while legal_moves != []:
    render(board.matrix)
    print("{}: it's your move.".format(current_player))
    print("Your possible moves: {}".format(list(set([x.coordinates for x in legal_moves]))))
    
    while proposed_move not in [x.coordinates for x in legal_moves]:
        proposed_move = validate_proposed_move(input('Propose a move:'))

    board.matrix = board.update(proposed_move, current_player, legal_moves)  
    current_player = alternate_player(current_player)
    legal_moves = board.find_legal_moves(current_player)

render(board.matrix)
print('Black pieces: {}'.format(board.count_pieces(board.BLACK)))
print('White pieces: {}'.format(board.count_pieces(board.WHITE)))

