#!/usr/bin/env python

from six.moves import input
from Board import Board
from reversiutils import alternate_player, render, validate_proposed_move

board = Board()

current_player = board.BLACK # Black moves first
legal_moves = board.find_legal_moves(current_player)

proposed_move = False

while legal_moves != []:
    render(board.matrix)
    print("{}: it's your move.".format(current_player))
    print("Your possible moves: {}".format(list(set([x.coordinates for x in legal_moves]))))
    
    while proposed_move not in [x.coordinates for x in legal_moves]:
        proposed_move = validate_proposed_move(input('Propose a move:'))

    board = board.update(proposed_move, current_player, legal_moves)  
    current_player = alternate_player(current_player)
    legal_moves = board.find_legal_moves(current_player)

render(board.matrix)
print('Black pieces: {}'.format(board.count_pieces(board.BLACK)))
print('White pieces: {}'.format(board.count_pieces(board.WHITE)))

